// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhuGpFCm1vhniVmLyvqjcC90v4ULTbZOs',
    appId: '1:365823477901:web:cf83cc5c9919a11927fac4',
    messagingSenderId: '365823477901',
    projectId: 'movie-app-ff280',
    authDomain: 'movie-app-ff280.firebaseapp.com',
    storageBucket: 'movie-app-ff280.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAI1Ww8DPYEwcrspoCFU9OAg9ZgZcpS7U',
    appId: '1:365823477901:android:5534dd8b121a9a4a27fac4',
    messagingSenderId: '365823477901',
    projectId: 'movie-app-ff280',
    storageBucket: 'movie-app-ff280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-qeAhmfPfKkVHqV7DMPuxKSQPm1WeIVw',
    appId: '1:365823477901:ios:051b4f5a9fd6e69c27fac4',
    messagingSenderId: '365823477901',
    projectId: 'movie-app-ff280',
    storageBucket: 'movie-app-ff280.appspot.com',
    androidClientId: '365823477901-o9fhisgg74ct3thp652vn3jdvqklk5ru.apps.googleusercontent.com',
    iosClientId: '365823477901-mtvmbql3aodpbg8ohtcatbs6mb2dsql3.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApplication',
  );
}
